apiVersion: v1
kind: Service
metadata:
  name: pet-department
spec:
  type: NodePort
  selector:
    app: pet-department
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30111
      targetPort: web
