apiVersion: v1
kind: Service
metadata:
  name: technology-department
spec:
  type: ClusterIP
  selector:
    app: technology-department
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
